# Generated by Django 3.0.8 on 2020-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200422_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_height_in_inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_sex',
            field=models.TextField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_weight_in_lbs',
            field=models.IntegerField(default=0),
        ),
    ]
