# Generated by Django 3.0.8 on 2020-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_food',
            field=models.TextField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_hobby',
            field=models.TextField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=0, max_length=5),
        ),
    ]
