# Generated by Django 3.0.8 on 2020-11-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201110_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='minutes_aerobic_exercise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='minutes_weightlifting_exercise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
